### ISSUE TITLE
Classe Strong

### ISSUE THREAD

**Issue by amedtler** [uLittleFat/projetinho#1]
Ao invés de utilizar a tag <b> experimente criar uma classe css somente com o atributo strong e utilize um span com essa classe CSS. 
Obs: não está errado utilizar <b>, mas se estiver dentro de uma classe, poderá ser manipulado de forma mais fácil no futuro.

**Comment by uLittleFat** [comment]
Ok!

**Comment by amedtler** [comment]
![Captura de tela de 2021-08-19 11-32-04](https://user-images.githubusercontent.com/734230/130087343-33f99866-13cf-4bc0-b1e2-3d36dc5c46bb.png)
 A tag <b> ainda permanece em alguns lugares. 
Vou fechar essa issue, pois como falei, não está errado, mas da forma que sugeri é o mais correto.
