### ISSUE TITLE
Diminuir fonte header-info__title

### ISSUE THREAD

**Issue by amedtler** [uLittleFat/projetinho#3]
Você utilizou o tamanho correto que estava no layout original, mas perceba que ficou diferente no browser, isso acontece pois existe uma variação de fonte entre o figma e o browser. Como o objetivo é deixar o mais próximo possível do layout, utilize a fonte com 48px que resolve.

**Comment by uLittleFat** [comment]
Corrigido !

**Comment by amedtler** [comment]
Ok
