### ISSUE TITLE
Section box 

### ISSUE THREAD

**Issue by amedtler** [uLittleFat/projetinho#7]
O background é um gradiente e não uma cor sólida. 
Pode usar esse [site](https://cssgradient.io/) para gerar, basta verificar as cores corretas no figma. 

Tente utilizar isso: 
background: rgb(248,248,248);
background: -moz-linear-gradient(0deg, rgba(248,248,248,1) 50%, rgba(255,255,255,1) 100%);
background: -webkit-linear-gradient(0deg, rgba(248,248,248,1) 50%, rgba(255,255,255,1) 100%);
background: linear-gradient(0deg, rgba(248,248,248,1) 50%, rgba(255,255,255,1) 100%);
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#f8f8f8",endColorstr="#ffffff",GradientType=1);

h3.box-list__title o tamanho correto é: 18px 

box-item: a cor da borda é essa: #DDDDDD pode deixar o vermelho para o efeito hover. 

O restante está ok.

**Comment by uLittleFat** [comment]
Não entendi muito bem sobre o gradiente!
Porém foram feitas as alterações !

**Comment by amedtler** [comment]
Ficou ok.
